export const people = [
  {
    name: "CC_MEMBER_1",
    description: "Chair",
    role: "CC Member",
    designation: "Chair",
    image: "/images/pfp.png",
  },
  {
    name: "CC_MEMBER_2",
    description: "Vice Chair",
    role: "CC Member",
    designation: "Vice Chair",
    image: "/images/pfp.png",
  },
  {
    name: "CC_MEMBER_3",
    description: "Web Master",
    role: "CC Member",
    designation: "Web Master",
    image: "/images/pfp.png",
  },
  {
    name: "CC_MEMBER_4",
    description: "Treasurer",
    role: "CC Member",
    designation: "Treasurer",
    image: "/images/pfp.png",
  },
  {
    name: "CC_MEMBER_5",
    description: "Secretary",
    role: "CC Member",
    designation: "Secretary",
    image: "/images/pfp.png",
  },
  {
    name: "CC_MEMBER_6",
    description: "Coordinator",
    role: "CC Member",
    designation: "Coordinator",
    image: "/images/pfp.png",
  },
  {
    name: "CC_MEMBER_7",
    description: "Coordinator",
    role: "CC Member",
    designation: "Coordinator",
    image: "/images/pfp.png",
  },
  {
    name: "CC_MEMBER_8",
    description: "Coordinator",
    role: "CC Member",
    designation: "Coordinator",
    image: "/images/pfp.png",
  },
  {
    name: "CC_MEMBER_9",
    description: "Coordinator",
    role: "CC Member",
    designation: "Coordinator",
    image: "/images/pfp.png",
  },
  {
    name: "CC_MEMBER_10",
    description: "",
    role: "CC Member",
    designation: "Member",
    image: "/images/pfp.png",
  },
  {
    name: "CC_MEMBER_11",
    description: "",
    role: "CC Member",
    designation: "Member",
    image: "/images/pfp.png",
  },
  {
    name: "CC_MEMBER_12",
    description: "",
    role: "CC Member",
    designation: "Member",
    image: "/images/pfp.png",
  },
  {
    name: "GM_MEMBER_1",
    description: "",
    role: "General Member",
    designation: "Member",
    image: "/images/pfp.png",
  },
  {
    name: "GM_MEMBER_2",
    description: "",
    role: "General Member",
    designation: "Member",
    image: "/images/pfp.png",
  },
  {
    name: "GM_MEMBER_3",
    description: "",
    role: "General Member",
    designation: "Member",
    image: "/images/pfp.png",
  },
];