export const people = [
  {
    name: "Dr. A. J. Shetty",
    description: "Chairman, LMET",
    role: "PATRON",
    designation: "Patron",
    image: "/images/team/executive-team/aj.jpg",
  },
  {
    name: "Mrs. Sharada J. Shetty",
    description: "Director, LMET",
    role: "PATRON",
    designation: "Patron",
    image: "/images/team/executive-team/sharada.png",
  },
  {
    name: "Mr. Prashanth Shetty",
    description: "Vice President, LMET",
    role: "PATRON",
    designation: "Patron",
    image: "/images/team/executive-team/prashant.png",
  },
  {
    name: "Mrs. Ashritha P. Shetty",
    description: "Director, LMET",
    role: "PATRON",
    designation: "PATRON",
    image: "/images/team/executive-team/Ashritha.png",
  },
  {
    name: "Dr. Prashanth Marla K",
    description: "Director, LMET",
    role: "PATRON",
    designation: "PATRON",
    image: "/images/team/executive-team/prashanth.jpg",
  },
  {
    name: "Dr. Amitha P. Marla",
    description: "Director, LMET",
    role: "PATRON",
    designation: "PATRON",
    image: "/images/team/executive-team/amitha.jpg",
  },
  {
    name: "Mr. Ranga B. Shetty",
    description: "Director, LMET",
    role: "PATRON",
    designation: "PATRON",
    image: "/images/team/executive-team/dir1.jpg",
  },
  {
    name: "Mrs. Vinuth R. Shetty",
    description: "Director, LMET",
    role: "PATRON",
    designation: "PATRON",
    image: "/images/team/executive-team/dir.jpg",
  },
  {
    name: "Dr. Shantharama Rai. C",
    description: "Principal, AJIET",
    role: "ADVISOR",
    designation: "Advisor",
    image: "/images/team/executive-team/principal.jpg",
  },
  {
    name: "Dr. P. Mahabaleshwarappa",
    description: "Dean Academics, AJIET",
    role: "ADVISOR",
    designation: "Advisor",
    image: "/images/team/executive-team/dean.jpg",
  },
  {
    name: "Dr. Antony P. J",
    description: "Vice Principal & HOD Dept Of CSE, AJIET",
    role: "ADVISOR",
    designation: "Advisor",
    image: "/images/team/executive-team/vice-principal.jpg",
  },
  {
    name: "Dr. Chanchal Antony",
    description: "HOD Dept. of AIML, AJIET",
    role: "MENTOR",
    designation: "Mentor",
    image: "/images/team/executive-team/mentor.jpg",
  },
  {
    name: "Darshan bhandary",
    description: "President, Enigma",
    role: "Core Committee",
    designation: "Core Committee",
    image: "/images/team/student-team/president.png",
  },
  {
    name: "Gauresh G Pai",
    description: "Web Dev, DevNation",
    role: "Core Committee",
    designation: "Core Committee",
    image: "/images/team/student-team/webdev.png",
  },
  {
    name: "Jnanesh",
    description: "Web Dev, DevNation",
    role: "Core Committee",
    designation: "Core Committee",
    image: "/images/team/student-team/jnanesh.jpeg",
  },
];
