export const people = [
  {
    name: "PATRON_1",
    description: "Chairman, TEAM FUTURE",
    role: "PATRON",
    designation: "Patron",
    image: "/images/pfp.png",
  },
  {
    name: "PATRON_2",
    description: "Founder Director, TEAM FUTURE",
    role: "PATRON",
    designation: "Patron",
    image: "/images/pfp.png",
  },
  {
    name: "PATRON_3",
    description: "Executive Director, TEAM FUTURE",
    role: "PATRON",
    designation: "Patron",
    image: "/images/pfp.png",
  },
  {
    name: "ADVISOR_1",
    description: "Principal, AJIET",
    role: "ADVISOR",
    designation: "Advisor",
    image: "/images/pfp.png",
  },
  {
    name: "ADVISOR_2",
    description: "Registrar, AJIET",
    role: "ADVISOR",
    designation: "Advisor",
    image: "/images/pfp.png",
  },
  {
    name: "ADVISOR_3",
    description: "Vice Principal, AJIET",
    role: "ADVISOR",
    designation: "Advisor",
    image: "/images/pfp.png",
  },
  {
    name: "ADVISOR_4",
    description: "Research Committee Convenor, AJIET",
    role: "ADVISOR",
    designation: "Advisor",
    image: "/images/pfp.png",
  },
  {
    name: "ADVISOR_5",
    description: "HOD CSE, AJIET",
    role: "ADVISOR",
    designation: "Advisor",
    image: "/images/pfp.png",
  },
  {
    name: "ADVISOR_6",
    description: "HOD CSE(DS), AJIET",
    role: "ADVISOR",
    designation: "Advisor",
    image: "/images/pfp.png",
  },
  {
    name: "ADVISOR_7",
    description: "HOD IT, AJIET",
    role: "ADVISOR",
    designation: "Advisor",
    image: "/images/pfp.png",
  },
  {
    name: "ADVISOR_8",
    description: "HOD CA, AJIET",
    role: "ADVISOR",
    designation: "Advisor",
    image: "/images/pfp.png",
  },
  {
    name: "ADVISOR_9",
    description: "HOD ECE, AJIET",
    role: "ADVISOR",
    designation: "Advisor",
    image: "/images/pfp.png",
  },
  {
    name: "ADVISOR_10",
    description: "HOD EE, AJIET",
    role: "ADVISOR",
    designation: "Advisor",
    image: "/images/pfp.png",
  },
  {
    name: "ADVISOR_11",
    description: "HOD ME, AJIET",
    role: "ADVISOR",
    designation: "Advisor",
    image: "/images/pfp.png",
  },
  {
    name: "MENTOR_1",
    description: "CSE Dept, AJIET",
    role: "MENTOR",
    designation: "Mentor",
    image: "/images/pfp.png",
  },
  {
    name: "MENTOR_2",
    description: "IT Dept, AJIET",
    role: "MENTOR",
    designation: "Mentor",
    image: "/images/pfp.png",
  },
  {
    name: "MENTOR_3",
    description: "CSE Dept, AJIET",
    role: "MENTOR",
    designation: "Mentor",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_1",
    description: "CSE Dept, AJIET",
    role: "Core Committee",
    designation: "Core Committee",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_2",
    description: "IT Dept, AJIET",
    role: "Core Committee",
    designation: "Core Committee",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_3",
    description: "CA Dept, AJIET",
    role: "Core Committee",
    designation: "Core Committee",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_4",
    description: "ECE Dept, AJIET",
    role: "Core Committee",
    designation: "Core Committee",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_5",
    description: "Library, AJIET",
    role: "Core Committee",
    designation: "Core Committee",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_6",
    description: "EE Dept, AJIET",
    role: "Core Committee",
    designation: "Core Committee",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_7",
    description: "ME Dept, AJIET",
    role: "Core Committee",
    designation: "Core Committee",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_8",
    description: "CSE (DS) Dept, AJIET",
    role: "Core Committee",
    designation: "Core Committee",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_9",
    description: "Graphics, Website, Media Publication",
    role: "Core Committee",
    designation: "Graphics, Website, Media Publication",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_10",
    description: "CSE Dept, AJIET",
    role: "Core Committee",
    designation: "Graphics, Website, Media Publication",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_11",
    description: "CSE(DS) Dept, AJIET",
    role: "Core Committee",
    designation: "Graphics, Website, Media Publication",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_12",
    description: "IT Dept, AJIET",
    role: "Core Committee",
    designation: "Graphics, Website, Media Publication",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_13",
    description: "IT Dept, AJIET",
    role: "Core Committee",
    designation: "Technical Committee",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_14",
    description: "ECE Dept, AJIET",
    role: "Core Committee",
    designation: "Technical Committee",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_15",
    description: "EE Dept, AJIET",
    role: "Core Committee",
    designation: "Technical Committee",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_16",
    description: "ECE Dept, AJIET",
    role: "Core Committee",
    designation: "Technical Committee",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_17",
    description: "CSE Dept, AJIET",
    role: "Core Committee",
    designation: "Technical Committee",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_18",
    description: "EE Dept, AJIET",
    role: "Core Committee",
    designation: "Technical Committee",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_19",
    description: "Technical Event Coordinator",
    role: "Core Committee",
    designation: "Technical Event Coordinator",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_20",
    description: "Technical Event Coordinator",
    role: "Core Committee",
    designation: "Technical Event Coordinator",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_21",
    description: "Technical Event Coordinator",
    role: "Core Committee",
    designation: "Technical Event Coordinator",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_22",
    description: "Technical Event Coordinator",
    role: "Core Committee",
    designation: "Technical Event Coordinator",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_23",
    description: "Technical Event Coordinator",
    role: "Core Committee",
    designation: "Technical Event Coordinator",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_24",
    description: "Infrastructure & Logistics",
    role: "Core Committee",
    designation: "Infrastructure & Logistics",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_25",
    description: "Sponsorship, PR & Fundraising",
    role: "Core Committee",
    designation: "Sponsorship, PR & Fundraising",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_26",
    description: "Outreach",
    role: "Core Committee",
    designation: "Outreach",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_27",
    description: "Registration",
    role: "Core Committee",
    designation: "Registration",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_28",
    description: "Media and Publication",
    role: "Core Committee",
    designation: "Media and Publication",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_29",
    description: "Media and Publication",
    role: "Core Committee",
    designation: "Media and Publication",
    image: "/images/pfp.png",
  },
  {
    name: "CORE_COMMITTEE_30",
    description: "Event Coordination",
    role: "Core Committee",
    designation: "Event Coordination",
    image: "/images/pfp.png",
  },
];
